### ISSUE TITLE
Main Page - Flickr Carousel

### ISSUE THREAD

**Issue by AxeFontaine** [TAMUSHPE/tamu-shpe-website#10]
### Overview
We want to display what we do at tamu shpe front and center with an image carousel that changes picture periodically

### Tasks
- [x] Connect to flickr using flickr api
- [x] Loop through images from "SHPE Mobile App" collection
- [x] Add transition animations and styles

Use mobile app git repo for guidance: https://github.com/TAMUSHPE/MobileApp/blob/main/src/components/FlickrPhotoGallery.tsx
