### ISSUE TITLE
Main Page - 5 Pillars Carousel

### ISSUE THREAD

**Issue by AxeFontaine** [TAMUSHPE/tamu-shpe-website#7]
### Overview
We want to display the organizations 5 pillars on the main page in a component that allows for scrolling

### Tasks
- [x] Create single pillar component
- [x] Create lists with information about each pillar
- [x] Iterate through lists
- [x] Add styling
