### ISSUE TITLE
Main Page - Our Sponsors Carousel

### ISSUE THREAD

**Issue by AxeFontaine** [TAMUSHPE/tamu-shpe-website#9]
### Overview
Need to showcase all of our sponsors in an infinitely scrolling list, use the design from figma

### Tasks
- [x] Implement "become a sponsor" button that routes to the sponsor page
- [x] Store sponsor images in the /public folder in the root directory
- [x] Create the list that scrolls infinitely
- [x] On hover stop the list from scrolling

Optional: Incorporate click and drag mouse scroll grabbing
